name:                ltexa
version:             0.3.0
github:              "0x00002a/ltexa"
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              "Natasha England-Elbro"
maintainer:          ""
copyright:           "2020 Natasha England-Elbro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/github0x00002a/ltexa#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
      - text
      - parsec
      - Stack
      - prettyprinter >= 1.7
      - optparse-applicative
      - bytestring
      - prettyprinter-ansi-terminal >= 1.1.2

executables:
  ltxa:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ltexa
    - text


tests:
  ltexa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ltexa
